# Site settings
title: Orientações Online sobre Portfólios
description: "Orientações Online sobre Portfólios"
url: "https://orientacoes-portfolios.github.io/"
author:
  name: "Filipe Falcão"
  email: "filipebatista@ic.ufal.br"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
